// <auto-generated />
namespace TaskManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newdata2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newdata2));
        
        string IMigrationMetadata.Id
        {
            get { return "202102270049591_newdata2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
