// <auto-generated />
namespace TaskManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newdata3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newdata3));
        
        string IMigrationMetadata.Id
        {
            get { return "202102270052210_newdata3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
